// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewoJhspxnb1bULI6g0eMNDZhSBNDoNAY',
    appId: '1:280150663713:web:ba9b33acda4f933597b960',
    messagingSenderId: '280150663713',
    projectId: 'livestock-941e6',
    authDomain: 'livestock-941e6.firebaseapp.com',
    storageBucket: 'livestock-941e6.appspot.com',
    measurementId: 'G-47R0EDXEWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDhmeVP08vvRJlxrbe3k3HI7oBwtHnSw',
    appId: '1:280150663713:android:b7b667d743467e8697b960',
    messagingSenderId: '280150663713',
    projectId: 'livestock-941e6',
    storageBucket: 'livestock-941e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADcOZaeMDoC-MsLhDn-GIkkQfqY2ocWqk',
    appId: '1:280150663713:ios:52226deb8a9d847097b960',
    messagingSenderId: '280150663713',
    projectId: 'livestock-941e6',
    storageBucket: 'livestock-941e6.appspot.com',
    iosClientId: '280150663713-td0rhu41vpj0p0p9rdtbsirh34tecfgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalYearApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADcOZaeMDoC-MsLhDn-GIkkQfqY2ocWqk',
    appId: '1:280150663713:ios:52226deb8a9d847097b960',
    messagingSenderId: '280150663713',
    projectId: 'livestock-941e6',
    storageBucket: 'livestock-941e6.appspot.com',
    iosClientId: '280150663713-td0rhu41vpj0p0p9rdtbsirh34tecfgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalYearApplication',
  );
}
